# Document:
# http://simiki.org/docs/configuration.html

url: 
title: LiYu's personal knowledge wiki
keywords: Technology, MachineLearning, DataMining, Economics
description: A wiki website of sthsf when I learned new knowledgy and technics.
author: LiYu

root: /wiki

deploy:
    - type: git
      remote: origin
      branch: gh-pages
      
theme: simple
